import { QuotationProduct } from './quotation-product';
import { QuotationParty } from './quotation-party';
import { BaseDO } from '../common/basedo';
export class Quotation extends BaseDO {
  quotationSeq: number;
  productId: string;
  productVersion: string;
  quotationDt: Date;
  quoteStatusCd: string;
  policyNum: string;
  proposalNum: string;
  quotationRefNum: string;
  genderCd: string;
  age: number;
  ageMonths: number;
  ageDays: number;
  occupationCd: string;
  smoker: string;
  proposerLASame: string;
  jointLife: string;
  signature: string;
  productTypeCd: string;
  productFamilyCd: string;
  policyYear: number;
  agentId: string;
  channel: string;
  subChannel: string;
  parentAgency: string;
  topupOptionCd: string;
  regularTopupFl: string;
  initialTopupFl: string;
  withdrawalFl: string;
  solverTypeCd: string;
  withdrawalRateTypeCd: string;
  // # online attributes
  childUserId: string;
  coverTypeCd: string;
  quotationExpiryDt: Date;
  isEditableQuoRefNumFl: string;
  uploadFlag: string;
  termTypeCd: string;
  pptermTypeCd: string;
  multiplierTypeCd: string;
  termCalculationBasisCd: string;
  isAgeEditableFl: string;
  issueDt: Date;
  quotAddtnlField1: string;
  quotAddtnlField2: string;
  quotAddtnlField3: string;
  quotAddtnlField4: string;
  quotAddtnlField5: string;
  quotAddtnlField6: string;
  quotAddtnlField7: string;
  quotAddtnlField8: string;
  quotAddtnlField9: string;
  quotAddtnlField10: string;
  payingYears: number;
  unselectedRiders: string;
  signatureDt: Date;

  leadId: string;
  fnaId: string;
  rpqId: string;
  agentSignature: string;
  visitedTabs: string;
  agentSignatureDt: Date;
  quotAddtnlField11: string;
  quotAddtnlField12: string;
  isBackDatedFl: string;
  insuranceTypeCd: string;
  tripTypeCd: string;
  maxTripPeriod: number;
  travelGeographyCd: string;
  visitPurposeCd: string;
  numberOfAdult: number;
  numberOfChildren: number;
  startDt: Date;
  endDt: Date;
  autoRegistrationNum: string;
  autoMakeCd: string;
  autoModelCd: string;
  appVersion: string;
  dbVersion: string;

  listQuotationProduct: QuotationProduct[];
  listQuotationParty: QuotationParty[];
}
